# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8621faf973a02433ce02649725c6fea072e54caf309eeebf6c4324b43dd3f494581311519786b12a928ae70dbbf645e888b56d443860f246dff213e7c295c7e3

test:
  secret_key_base: 328bf376553a33650959e515cc8c41d1655abc6540bade0edf5dc3a7e91abacd0f7ae1e1bf4c3f888673ce74bad444123bcec29dfee2a1f9a39ffb092349de54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
